name: Build Linux AppImage

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 26
      uses: actions/setup-java@v4
      with:
        java-version: '26'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build and Copy Dependencies with Maven
      run: |
        mvn clean compile -f adam/pom.xml -U
        mvn dependency:copy-dependencies -f adam/pom.xml -DoutputDirectory=target/deps

    - name: Run jpackage
      run: |
        jpackage \
          --type app-image \
          --name "HyOS" \
          --module-path adam/target/deps:adam/target/classes \
          --module com.adam/com.adam.HyOS \
          --dest target/appimage-out

    - name: Download appimagetool
      run: |
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage

    - name: Build Final AppImage
      run: |
        ./appimagetool-x86_64.AppImage target/appimage-out/HyOS

    - name: Upload AppImage Artifact
      uses: actions/upload-artifact@v4
      with:
        name: HyOS-Linux
        path: "*.AppImage"
